blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogsite.urls', namespace="blogsite")),
]

blogsite/urls.py
from django.urls import path

from . import views

app_name = 'blogsite'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_post', views.create_post, name='create_post'),
    path('get_post/<int:post_id>', views.get_post, name='get_post'),
]

blogsite/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.TextField()

    def get_absolute_url(self):
        return reverse('blog_post_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['created_on']

        def __unicode__(self):
            return self.title


class Comment(models.Model):
    name = models.CharField(max_length=42)
    email = models.EmailField(max_length=75)
    website = models.URLField(max_length=200, null=True, blank=True)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

blogsite/forms.py
from django import forms  

class PostForm(forms.Form):  
    title = forms.CharField(label="Title",max_length=255)
    content = forms.CharField(label="Content")
    author = forms.CharField(label="Author")

blogsite/views.py
from django.shortcuts import render
from django.http import HttpResponse
from blogsite.models import Post
from blogsite.forms import PostForm  

def index(request):
    posts = Post.objects.all()
    context_dict = {'posts': posts}
    return render(request, 'index.html', context_dict)

def get_post(request, post_id):
    post=Post.objects.get(id=post_id)
    context_dict = {'post': post}
    print(post)
    return render(request, 'show_post.html', context_dict)

def create_post(request):
    if "GET" == request.method:
        post = PostForm() 
        return render(request, 'create_post.html', {'form': post })
    else:
        request.POST["title"]
        b = Post(title=request.POST["title"], content=request.POST["content"], author=request.POST["author"])
        b.save()
        return render(request, 'successful_post_creation.html', {})

blogsite/templates/create_post.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Create Post</title>  
</head>  
<body>  
<form method="POST" class="post-form" action="{% url "blogsite:create_post" %}">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit" class="save btn btn-default">Create</button>  
</form>
<a href='/'>Click here to go to index page.</a>  
</body>  
</html>

blogsite/templates/index.html
Posts 
<ol>
    {% for post in posts %}
        <li><a href="/get_post/{{ post.id }}"> {{ post.title }}</a></li>
    {% endfor %}
</ol>

<a href="/create_post">Create Post</a>

blogsite/templates/show_post.html
<h1>
    {{ post.title }}
</h1>

<h1>
    {{ post.content }}
</h1>

<a href='/'>Click here to go to index page.</a>

blogsite/templates/successful_post_creation.html
Post Created Successfully. 

<a href='/'>Click here to go to index page.</a>